services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wb-api-app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /etc/localtime:/etc/localtime:ro
    # Явно указываем, что нужно использовать .env файл
    env_file:
      - .env
    depends_on:
      - db

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wb-api-scheduler
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /etc/localtime:/etc/localtime:ro
    # И сюда тоже обязательно добавляем env_file!
    env_file:
      - .env
    depends_on:
      - app # Зависимость от app не обязательна, но и не мешает
    command: php artisan schedule:work

  nginx:
    image: nginx:alpine
    container_name: wb-api-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: wb-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wb_test
      MYSQL_USER: wb_user
      MYSQL_PASSWORD: wb_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
